import type { Metadata } from "next";
import "./globals.css";
import { Lilita_One } from "next/font/google";
import { lilita_one } from "@/utils/fonts";


export const metadata: Metadata = {
  title: "Tic Tac Toe",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-stone-300">
      <body className={`${lilita_one}`}>{children}</body>
    </html>
  );
}
